= Messaging Functions
//Aliases
:conum-guard-sh: #
ifndef::icons[:conum-guard-sh: # #]

:conum-guard-java: //
ifndef::icons[:conum-guard-java: // //]

This demo will show how to integrate OpenWhisk Functions with Messaging Brokers using https://github.com/apache/incubator-openwhisk/blob/master/docs/feeds.md[Feeds] and https://github.com/apache/incubator-openwhisk/blob/master/docs/triggers_rules.md[Triggers]

This polyglot demo of functions that does splitting, sorting, uppercase of the string message that was received on messaging endpoint, and  will post the processed on to another configured reply messaging endpoint.

This is demo can be used is DIY guide following the instructions or you can navigate to **solutions** folder to just do a build and deploy of the functions directly.

== Pre-requisite

The following languages are used in the demo, hence its recommended to have the latest version of the language and tools installed.

- Python 
- Golang
- Java with Maven
- Node

[IMPORTANT]
====
You have an OpenWhisk deployed on to OpenShift.  If not refer to link:../../README.adoc#setup-openwhisk[Deploy OpenWhisk] to see how to deploy OpenWhisk on to OpenShift
====

== Overview 

The demo  uses the https://www.amqp.org/[AMQP] based OpenWhisk Feed and Action from https://github.com/kameshsampath/amqp-wsk-feed (`openshift` branch), for the convenience the pre-build docker image of the feed provider is available at `kameshsampath/amqp-wsk-feed`.

The demo uses https://activemq.apache.org/artemis/[Apache Artemis] as the message broker that will connected via https://www.amqp.org/[AMQP].  You are free to use any https://www.amqp.org/[AMQP] supported broker that can be deployed to OpenShift.

== Build and Deploy 

Clone the repo http://bit.ly/adv-faas-tutorial[Advanced FaaS Tutorial], we call this folder as `$PROJECT_HOME`.  Navigate to solutions/messaging-functions folder.

== Create OpenShift project

Let us create a new project say `msgdemo` for deploying applications of this demo.

[source,sh,subs=attributes+]
-----
oc new-project msgdemo
-----

[[deploy-artemis]]
=== Apache Artemis

[source,sh,subs=attributes+]
----
oc apply -f openshift/apache-artemis.yml {conum-guard-sh} # <1>
----

<1> This will deploy Apache Artemis Broker to the msgdemo project

=== Deploy AMQP Feed Provider

[source,sh,subs=attributes+]
----
git clone https://github.com/cliffjansen/amqp-wsk-feed.git
cd amqp-wsk-feed
oc project openwhisk
./deploy/ocWhiskSystem.sh {conum-guard-sh} # <1>
----

==== Create Package

All the functions that will be created for the split, sort, upper case and sender  will be grouped under the OpenWhisk package called `msgdemo`.  Run the following command to create the `msgdemo` package:

[source,sh,subs=attributes+]
----
wsk -i package update -p brokerHost 'apache-artemis.msgdemo' -p brokerPort '5672' -p connection_options '{"host": "apache-artemis.msgdemo", "port": 5672 }' msgdemo
----

- The Message Broker host, if you have deployed <<deploy-artemis>> in the same OpenShift project or update the host name to point to broker url 
- The AMQP port of the broker which bu default is `5672`
- The https://github.com/amqp/rhea[AMQP/rhea] module options that is required by the provider to connect to Message Broker

=== Split, Sort, Upper Case and Sender Functions

As this will be a polyglot application, we will write each one of the split, sort, uppercase and sender in four different programming language:

- **Python** - Split
- **Go** - Sort
- **Java** - UpperCase
- **JavaScript** - Message Sender

==== Split Action

Lets create the splitter action in `Python`, create a file called `splitter.py` and add the following contents to it:

[source,python]
----
import json
def main(args):
    body = json.loads(args["body"])
    text = body.get("text", "NODATA")
    replyTo = body.get("replyTo", "DLQ")
    print("Got Message : %s, \n Reply Queue: %s \n" %
          (text, replyTo))
    r = {}
    r["result"] = text.split(",")
    r["replyTo"] = replyTo
    return r
----

Lets deploy the function using the following command,

[source,sh,subs=attributes+]
----
cd $PROJECT_HOME/integration/messaging-functions/solutions
wsk -i action update msgdemo/splitter split.py
----

==== Uppercase Action

The Uppercase action will be Java based function.

This Action will take the array of Strings from previous step (Splitter Action) and convert the strings to upper case

[source,sh,subs=attributes+]
----
cd ..
mvn archetype:generate \
  -DarchetypeGroupId=org.apache.openwhisk.java \
  -DarchetypeArtifactId=java-action-archetype \
  -DarchetypeVersion=1.0-SNAPSHOT \
  -DgroupId=com.example \
  -DartifactId=uppercase \
  -Dversion=1.0-SNAPSHOT \
  -DinteractiveMode=false
----

Update the FunctionApp class with this code:
[source,java,subs=attributes+]
----
  public static JsonObject main(JsonObject args) {
    JsonObject response = new JsonObject();
    JsonArray upperArray = new JsonArray();
    if (args.has("result")) {
        args.getAsJsonArray("result").forEach(e -> upperArray.add(e.getAsString().toUpperCase()));
    }
    String replyQ = "DLQ";
    if (args.has("replyTo")) {
        replyQ = args.getAsJsonPrimitive("replyTo").getAsString();
    }
    response.addProperty("replyTo", replyQ);
    response.add("result", upperArray);
    return response;
  }
----

<1> The function expects the previous action in sequence to send the parameter with JSON attribute called `result`

Update the FunctionAppTest testFunction method with code:
[source,java,subs=attributes+]
----
  @Test
  public void testFunction() {
    JsonObject args = new JsonObject();
    JsonArray splitStrings = new JsonArray();
    splitStrings.add("apple");
    splitStrings.add("orange");
    splitStrings.add("banana");
    args.add("result", splitStrings);
    JsonObject response = FunctionApp.main(args);
    assertNotNull(response);
    JsonArray results = response.getAsJsonArray("result");
    assertNotNull(results);
    assertEquals(3, results.size());
    List<String> actuals = new ArrayList<>();
    results.forEach(j -> actuals.add(j.getAsString()));
    assertTrue(actuals.contains("APPLE"));
    assertTrue(actuals.contains("ORANGE"));
    assertTrue(actuals.contains("BANANA"));
  }
----

===== Build Uppercase Action
[source,sh,subs=attributes+]
----
cd $PROJECT_HOME/integration/messaging-functions/solutions/uppercase
mvn clean package
wsk -i action update msgdemo/uppercase target/uppercase.jar --main com.example.FunctionApp
----

==== Sort Action

Lets create the splitter action in `Go`, this Action will take the array of Strings from previous step (UpperCase Action) and sort the strings in alphabetical order.

Create a file called `sorter.go` and add the following contents to it:

[source,go]
----
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
)

func main() {

	arg := os.Args[1]
	fmt.Printf("Req %+v \n", arg)

	type Request struct {
		ReplyTo string   `json:"replyTo"`
		Result  []string `json:"result"`
	}

	//parse request
	var req Request
	err := json.Unmarshal([]byte(arg), &req)

	if err != nil {
		fmt.Println("error:", err)
	}

	//sort
	s := req.Result
	sort.Strings(s)

	//rebuild response
	res := &Request{
		ReplyTo: req.ReplyTo,
		Result:  s,
	}
	resJSON, _ := json.Marshal(res)

	fmt.Println(string(resJSON))
}
----

Lets deploy the function using the following command,

[source,sh,subs=attributes+]
----
cd $PROJECT_HOME/integration/messaging-functions/solutions
rm exec && rm /tmp/exec.zip
GOOS=linux GOARCH=amd64 go build -o exec
zip /tmp/exec.zip exec
wsk -i action update msgdemo/sorter --native /tmp/exec.zip
----

==== Message Sender Action

The Message Sender Action is responsible for sending the sorted array of Strings from previous step (Sorter Action) as a message back to `replyTo`. `replyTo` will be sent as part of the request from the sender when sending the message to the desired messaging endpoint.  If `replyTo` is not available as part of the request the response will be delivered to `DLQ`.

[source,sh,subs=attributes+]
----
mkdir -p $PROJECT_HOME/sender
cd $PROJECT_HOME/sender
----

Create a file called `package.json` with the following contents:
[source,json]
----
{
  "name": "sender",
  "version": "1.0.0",
  "description": "Sends message using AMQP protocol",
  "main": "sender.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "rhea": "^0.2.11"
  }
}

----

Create a file called `msgsender.js` with the following contents:

[source,js]
----
var container = require('rhea');
const uuidv4 = require('uuid/v4');

function sendMessage(args) {

    console.log("ReplyTo: " + args.replyTo)
    console.log("Request: " + args.result)

    var result = args.result

    return new Promise(function (resolve, reject) {
        var msg = { message_id: uuidv4(), body: { 'result': result } };
        container.on('sendable', function (context) {
            if (context.sender.sendable()) {
                context.sender.send(msg)

            }
            //TODO error handling reject
        });

        container.on('accepted', function (context) {
            console.log('Messages acknowledged');
            resolve({
                "response": msg
            })
            context.connection.close();
            //TODO error handling reject
        });
        container.connect({ port: args.brokerPort, host: args.brokerHost }).open_sender(args.replyTo);
    });
}
exports.main = sendMessage;
----

[source,sh,subs=attributes+]
----
cd $PROJECT_HOME/integration/messaging-functions/solutions/sender
npm install
( rm -f /tmp/msgsender.zip && zip -qr /tmp/msgsender.zip * )
wsk -i action update msgdemo/msgsender --kind nodejs:8 /tmp/msgsender.zip
----

[[create-trigger]]
=== Create Trigger

The trigger is responsible for connecting rule with feeds, in this case to connect the action that needs to be fired when a message is dropped in the configured Queue.

[source,sh,subs=attributes+]
----
wsk -i trigger create trig_queue_99 --feed /whisk.system/amqp/amqpFeed  -p address queue_99 -p connection_options '{"host": "apache-artemis.msgdemo", "port": 5672 }' {conum-guard-sh} # <1>
wsk -i action update splitsortucase --sequence msgdemo/splitter,msgdemo/uppercase,msgdemo/sorter,msgdemo/msgsender 
wsk -i rule update rule_splitsortucase trig_queue_99 splitsortucase {conum-guard-sh} # <2>
----

<1> Create a trigger with feed as `/whisk.system/amqp/amqpFeed` listening to messaging address `queue_99`
<2> A Sequence of actions that will receive the `text` from the Queue queue_99, then will split, sort, uppercase the next strings and send it to the destination configured via `replyTo`

=== Testing 
[source,sh,subs=attributes+]
----
cd $PROJECT_HOME
cd integration/messaging-functions/solutions/test
npm install rhea
oc project msgdemo
----

==== Terminal I

[source,sh,subs=attributes+]
----
ARTEMIS_IP=$(minishift ip)
ARTEMIS_PORT=$(oc get svc apache-artemis -o=jsonpath='{.spec.ports[0].nodePort}')
node demorecv.js $ARTEMIS_IP $ARTEMIS_PORT replyQ99 {conum-guard-sh} # <1>
----

<1> **replyQ99**  is the messaging destination where the response will be posted (**replyTo** destination described above)

==== Terminal II

[source,sh,subs=attributes+]
----
ARTEMIS_IP=$(minishift ip)
ARTEMIS_PORT=$(oc get svc apache-artemis -o=jsonpath='{.spec.ports[0].nodePort}')
node demosend.js $ARTEMIS_IP $ARTEMIS_PORT queue_99 '{ "text": "football,cricket,basketball,rugby", "replyTo": "replyQ99"}' {conum-guard-sh} # <1>
wsk -i activation poll 
----

<1> **queue_99** is the address where we have configured the trigger,**replyQ99**  is the messaging destination where the response will be posted (**replyTo** destination described above)

=== Utils

You can find lot examples to use `amqp/rhea` at the https://github.com/amqp/rhea[amqp/reha] which you can use to send or receive the messages.

=== Cleanup

To clear all actions, triggers, rules and packages that are created as part of this demo, run the following command:

[source,sh,subs=attributes+]
----
cd $PROJECT_HOME/integration/messaging-functions/solutions/
./cleanup.sh
----
